authors = [
    { 'user_href': 'https://api.stormpath.com/v1/accounts/26bgM8tHF8clJCykQvIFCJ',
      'name': 'Gary Shteyngart',
      'bio': '',
      'picture': '',
      'website': '',
      'blog': '',
      'twitter_id': '',
    },
    { 'user_href': 'https://api.stormpath.com/v1/accounts/3khGRYGq2lV5qr38wcKkyt',
      'name': 'Anne Mendelson',
      'bio': '',
      'picture': '',
      'website': '',
      'blog': '',
      'twitter_id': '',
    },
    { 'user_href': 'https://api.stormpath.com/v1/accounts/5fA9mLkcLzqjWKdEQYMu1f',
      'name': 'Students Of Cardozo And Woodrow Wilson High Schools',
      'bio': '',
      'picture': '',
      'website': '',
      'blog': '',
      'twitter_id': '',
    },
    { 'user_href': 'https://api.stormpath.com/v1/accounts/UCVcjOyVlZ1JJr9h8juBw',
      'name': 'Neal Gabler',
      'bio': '',
      'picture': '',
      'website': '',
      'blog': '',
      'twitter_id': '',
    },
    { 'user_href': 'https://api.stormpath.com/v1/accounts/6I9ajdt9RdpDAvRw6XodWW',
      'name': 'James P. Othmer',
      'bio': '',
      'picture': '',
      'website': '',
      'blog': '',
      'twitter_id': '',
    },
    { 'user_href': 'https://api.stormpath.com/v1/accounts/3DgoAqMV2hs2zXu9XN7rfY',
      'name': 'Jake Hartnell',
      'bio': 'Jake Hartnell was raised in the suburban sprawl of Chicago in a very conservative evangelical Christian family. After becoming disillusioned with his faith, he ran away to England to attend the University of Manchester and help found the record label Superstar Destroyer and his band Unconscious Jungle. After numerous adventures + hardships he journeyed across the seas yet again to come to UC Berkeley, where he studies computer science, Internet economics, digital publishing technology, and whatever else interests him. He currently works as a developer and product manager at Hypothes.is (a non-profit tech company working with web annotation), but is also a contributor to the open source project Epub.js, writer, and musician. He has already begun work on his next book entitled "How to become a better Christian by becoming an Atheist (and Visa Versa)."',
      'picture': 'static/images/jake_hartnell_author.jpg',
      'website': 'http://hypothes.is/',
      'blog': 'http://www.jakehartnell.com/',
      'twitter_id': 'http://www.twitter.com/JakeHartnell',
    }
]

books = [
    { 'title': "Super Sad True Love Story",
      'author': "Gary Shteyngart",
      'publisher': "Random House",
      'genres': ["Fiction","Romance"],
      'cover_large': "static/images/super_sad_true_love_story.large.jpg",
      'cover_thumb': "static/images/super_sad_true_love_story.thumb.jpg",
    },
    { 'title': "Milk",
      'author': "Anne Mendelson",
      'publisher': "Knopf",
      'genres': ["Non-Fiction", "Food"],
      'cover_large': "static/images/milk.large.jpg",
      'cover_thumb': "static/images/milk.thumb.jpg"
    },
    { 'title': "Milk2",
      'author': "Anne Mendelson",
      'publisher': "Knopf",
      'genres': ["Non-Fiction", "Food"],
      'cover_large': "",
      'cover_thumb': ""
    },
    { 'title': "Winchell",
      'author': "Neal Gabler",
      'publisher': "Vintage",
      'genres': ["Non-Fiction", "Biographies"],
      'cover_large': "static/images/winchell.large.jpg",
      'cover_thumb': "static/images/winchell.thumb.jpg",
    },
    { 'title': "Get Used To The Seats",
      'author': "Students Of Cardozo And Woodrow Wilson High Schools",
      'publisher': "826DC",
      'genres': ["Non-Fiction"],
      'cover_large': "static/images/get_used_to_the_seats.large.jpg",
      'cover_thumb': "static/images/get_used_to_the_seats.thumb.jpg"
    },
    { 'title': "Adland",
      'author': "James P. Othmer",
      'publisher': "Anchor",
      'genres': ["Non-Fiction", "Advertising"],
      'cover_large': "static/images/adland.large.jpg",
      'cover_thumb': "static/images/adland.thumb.jpg"
    },
    { 'title': "23rd Century Romance",
      'author': "Jake Hartnell",
      'publisher': "Self",
      'genres': ["Fiction", "Sci-Fi"],
      'cover_large': "",
      'cover_thumb': "static/images/23rdcenturyromance.thumb.jpg"
    },
    { 'title': "How to become a better Christian by becoming an Atheist (and visa versa)",
      'author': "Jake Hartnell",
      'publisher': "Self",
      'genres': ["Non-Fiction", "Religion", "Atheism", "Spirituality", "Comedy"],
      'cover_large': "",
      'cover_thumb': "static/images/Raptor_Jesus_by_DangermouseDavs.jpg"
    },
    { 'title': "Blood",
      'author': "Jake Hartnell",
      'publisher': "Self",
      'genres': ["Sci-Fi", "Evolution", "Fiction"],
      'cover_large': "",
      'cover_thumb': "static/images/1658.jpg"
    },
]