"""empty message

Revision ID: 23f24d4c34b
Revises: 195c62040c35
Create Date: 2014-05-06 19:48:17.747788

"""

# revision identifiers, used by Alembic.
revision = '23f24d4c34b'
down_revision = '195c62040c35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('test_column', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'test_column')
    ### end Alembic commands ###
