"""empty message

Revision ID: 59929ff806f8
Revises: 1975f72e0bf4
Create Date: 2014-05-08 14:27:54.186372

"""

# revision identifiers, used by Alembic.
revision = '59929ff806f8'
down_revision = '1975f72e0bf4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('ios_token', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'ios_token')
    ### end Alembic commands ###
